/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const afterNavigate: typeof import('$app/navigation')['afterNavigate']
  const afterUpdate: typeof import('svelte')['afterUpdate']
  const beforeNavigate: typeof import('$app/navigation')['beforeNavigate']
  const beforeUpdate: typeof import('svelte')['beforeUpdate']
  const browser: typeof import('$app/environment')['browser']
  const building: typeof import('$app/environment')['building']
  const createEventDispatcher: typeof import('svelte')['createEventDispatcher']
  const derived: typeof import('svelte/store')['derived']
  const dev: typeof import('$app/environment')['dev']
  const get: typeof import('svelte/store')['get']
  const goto: typeof import('$app/navigation')['goto']
  const invalidate: typeof import('$app/navigation')['invalidate']
  const invalidateAll: typeof import('$app/navigation')['invalidateAll']
  const navigating: typeof import('$app/stores')['navigating']
  const onDestroy: typeof import('svelte')['onDestroy']
  const onMount: typeof import('svelte')['onMount']
  const page: typeof import('$app/stores')['page']
  const preloadCode: typeof import('$app/navigation')['preloadCode']
  const preloadData: typeof import('$app/navigation')['preloadData']
  const readable: typeof import('svelte/store')['readable']
  const tick: typeof import('svelte')['tick']
  const toast: typeof import('svelte-sonner')['toast']
  const updated: typeof import('$app/stores')['updated']
  const version: typeof import('$app/environment')['version']
  const writable: typeof import('svelte/store')['writable']
}
