# Air 热更新配置文件
# 官方文档: https://github.com/cosmtrek/air

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # 执行的命令
  cmd = "go build -o ./tmp/main ./cmd/myblog"
  # 二进制文件名
  bin = "tmp/main"
  # 编译完成后是否立即运行
  full_bin = "./tmp/main"
  # 监听的文件扩展名
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "json"]
  # 排除的文件扩展名
  exclude_ext = ["txt", "md"]
  # 监听的目录
  include_dir = []
  # 排除的目录
  exclude_dir = ["tmp", "vendor", "testdata", "logs", ".git", ".vscode", ".idea"]
  # 排除的文件
  exclude_file = []
  # 排除的正则表达式
  exclude_regex = ["_test.go"]
  # 排除的文件名
  exclude_unchanged = false
  # 如果文件更改过于频繁，则停止运行
  stop_on_fail = false
  # 发送中断信号前的延迟时间
  send_interrupt = false
  # 发送中断信号后的延迟时间
  kill_delay = "0s"
  # 重新构建延迟
  rerun = false
  # 重新构建间隔
  rerun_delay = 500
  # 添加额外的参数传递给go build命令
  args_bin = []

[log]
  # 显示日志时间
  time = false
  # 只显示主要日志
  main_only = false

[color]
  # 自定义每个部分显示的颜色
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  # 在启动时删除tmp目录
  clean_on_exit = true

# 可以在这里定义多个命令，用于在启动前/后执行
# [misc.pre_cmd]
# [misc.post_cmd]